# ArgoCD configuration (AWS sbx)
# Admin account enabled for initial access (OIDC added in follow-up)
nameOverride: argo
global:
  domain: argo.sbx.rbcn.ai
repoServer:
  extraArgs:
    - --repo-cache-expiration=15m
server:
  ingress:
    enabled: true
    ingressClassName: kong
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-route53-dns
    hosts:
      - argo.sbx.rbcn.ai
    tls:
      - secretName: argo-le-tls
        hosts:
          - argo.sbx.rbcn.ai
configs:
  cm:
    create: true
    url: https://argo.sbx.rbcn.ai
    admin.enabled: true
    timeout.reconciliation: 30s
  rbac:
      create: true
      policy.default: role:admin
      scopes: '[roles]'
      policy.csv: |
        #################################################
        # Policy rules are in the form:
        #   p, subject, resource, action, object, effect
        # Role definitions and bindings are in the form:
        #   g, subject, inherited-subject
        #################################################

        ################### GROUPS #####################
        g, maintain, role:admin
        ################### POLICIES #####################
        # role:sync-only
        p, role:sync-only, applications, get, *, allow
        p, role:sync-only, applications, sync, *, allow
        p, role:sync-only, applications, action/apps/*/restart, *, allow
        p, role:sync-only, applications, action/batch/CronJob/create-job, *, allow
        p, role:sync-only, logs, get, chat/*, deny

        # role:no-access
        p, role:no-access, *, *, *, deny

        # maintainers are kings here and only here
        # role:admin
        p, role:admin, *, *, *, allow
extraObjects: []
