# RabbitMQ Cluster for AWS EKS
# Uses RabbitMQ Operator CRD
apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbitmqcluster-chat
  namespace: unique
spec:
  image: rabbitmq:3.13-management
  replicas: 1
  resources:
    requests:
      cpu: '200m'
      memory: 1Gi
    limits:
      memory: 1Gi
  rabbitmq:
    additionalConfig: |
      cluster_partition_handling = pause_minority
      disk_free_limit.relative = 1.0
      collect_statistics_interval = 10000
  persistence:
    storageClassName: gp3
    storage: "10Gi"
  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                - rabbitmqcluster-chat
          topologyKey: kubernetes.io/hostname
  override:
    statefulSet:
      spec:
        template:
          spec:
            containers:
            - name: rabbitmq
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
            initContainers:
            - name: setup-container
              securityContext:
                privileged: false
                allowPrivilegeEscalation: false
            # nodeSelector removed - sbx nodes don't have these labels
            topologySpreadConstraints:
            - maxSkew: 1
              topologyKey: "topology.kubernetes.io/zone"
              whenUnsatisfiable: ScheduleAnyway
              labelSelector:
                matchLabels:
                  app.kubernetes.io/name: rabbitmqcluster-chat
