# ClusterSecretStore for AWS Secrets Manager
# Apply after external-secrets is deployed
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cluster-secrets
  namespace: external-secrets
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::696630818863:role/acme-dogfood-sbx-euc2-cluster-secrets"
---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: aws-secrets-manager
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-central-2
      auth:
        jwt:
          serviceAccountRef:
            name: cluster-secrets
            namespace: external-secrets
