# Configuration (theme) backend service configuration (AWS sbx)

image:
  repository: <ECR_REGISTRY_THIRDPARTY>/backend-service-configuration
  tag: "2026.14.1"

extraEnvSecrets:
  - configuration-secrets
