spec:
  name: backend-service-configuration
  autoSync: false
  sources:
    - repoURL: 'https://github.com/unique-ag/hello-aws'
      targetRevision: deploy/sbx
      ref: values
    - repoURL: ghcr.io/unique-ag/helm-charts
      chart: backend-service
      targetRevision: 10.3.0
      helm:
        releaseName: backend-service-configuration
        valueFiles:
          - $values/06-applications/defaults/backend-services/configuration.yaml
          - $values/06-applications/sbx/values/backend-services/_all.yaml
          - $values/06-applications/sbx/values/backend-services/configuration.yaml
        valuesObject: {}
