spec:
  name: backend-service-configuration
  autoSync: false
  sources:
    - repoURL: ghcr.io/unique-ag/helm-charts
      chart: backend-service
      targetRevision: 10.3.0
      helm:
        releaseName: backend-service-configuration
        valueFiles:
          - $values/06-applications/defaults/backend-services/configuration.yaml
          - $values/06-applications/sbx/value-overlays/backend-services/_all.yaml
          - $values/06-applications/sbx/value-overlays/backend-services/configuration.yaml
        valuesObject:
          image:
            tag: "2026.24.0"
