name: '[tf] Validate'
on:
  pull_request:
    paths:
      - '0[1-5]-*/**/*.tf'
      - 'modules/**/*.tf'
      - 'scripts/**'
      - '.github/workflows/tf.validate.yaml'

permissions:
  contents: read

jobs:
  validate:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - layer: bootstrap
            dir: 01-bootstrap
          - layer: governance
            dir: 02-governance
          - layer: infrastructure
            dir: 03-infrastructure
          - layer: data-and-ai
            dir: 04-data-and-ai
          - layer: compute
            dir: 05-compute
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
        with:
          terraform_version: '1.14.0'
      - name: fmt
        run: terraform -chdir=${{ matrix.dir }}/terraform fmt -check -recursive
      - name: init
        run: terraform -chdir=${{ matrix.dir }}/terraform init -backend=false
      - name: validate
        run: terraform -chdir=${{ matrix.dir }}/terraform validate -no-color
      - name: tflint
        uses: terraform-linters/setup-tflint@6e87008f9dd1fe3e34e66aca6c97b4a69f72a7f4 # v4
      - run: |
          tflint --init
          tflint --chdir=${{ matrix.dir }}/terraform
      - name: trivy
        uses: aquasecurity/trivy-action@57a97c7e7821a5776cebc9bb87c984fa69cba8f1 # v0.35.0
        with:
          scan-type: fs
          scan-ref: ${{ matrix.dir }}/terraform
          scanners: misconfig
          severity: HIGH,CRITICAL
          trivyignores: .trivyignore
      - name: checkov
        uses: bridgecrewio/checkov-action@de2bfaecd21d58ef232e0d2a3391c33c32c460d7 # v12.3096.0
        with:
          directory: ${{ matrix.dir }}/terraform
          framework: terraform
          quiet: true
